name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8 (fail on syntax or undefined names)
        run: |
          echo "Checking for syntax errors or undefined names..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests with pytest
        run: |
          echo "Running unit tests..."
          pytest
